//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LobbyProtocol.proto
// Note: requires additional types generated from: EpochProtocol.proto
namespace LobbyProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_QueryQuest")]
  public partial class CS_QueryQuest : global::ProtoBuf.IExtensible
  {
    public CS_QueryQuest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}